-- INIT DATABASE FOR ROOM BOOKING SYSTEM (PostgreSQL)
-- Converted from documents/sql/init_tables.sql (MSSQL)
-- Identifiers are unquoted → stored as lowercase (admins, roles, ...)
-- ============================================

-- ===== USER & AUTH =====
CREATE TABLE admins (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    full_name VARCHAR(255),
    status VARCHAR(50) DEFAULT 'ACTIVE'
);

CREATE TABLE roles (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE permissions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(100) NOT NULL UNIQUE,
    description VARCHAR(255)
);

CREATE TABLE admin_roles (
    admin_id INTEGER NOT NULL,
    role_id INTEGER NOT NULL,
    PRIMARY KEY (admin_id, role_id),
    FOREIGN KEY (admin_id) REFERENCES admins(id),
    FOREIGN KEY (role_id) REFERENCES roles(id)
);

CREATE TABLE role_permissions (
    role_id INTEGER NOT NULL,
    permission_id INTEGER NOT NULL,
    PRIMARY KEY (role_id, permission_id),
    FOREIGN KEY (role_id) REFERENCES roles(id),
    FOREIGN KEY (permission_id) REFERENCES permissions(id)
);

CREATE TABLE users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    phone VARCHAR(20),
    password_hash VARCHAR(255) NOT NULL,
    full_name VARCHAR(255),
    status VARCHAR(50) DEFAULT 'ACTIVE'
);

-- ===== ROOM & BOOKING =====
CREATE TABLE loaiphong (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ten_loai VARCHAR(100) NOT NULL,
    gia_co_ban DECIMAL(18,2) NOT NULL
);

CREATE TABLE phong (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    so_phong VARCHAR(20) NOT NULL UNIQUE,
    loai_phong_id INTEGER NOT NULL,
    trang_thai VARCHAR(50) DEFAULT 'AVAILABLE',
    FOREIGN KEY (loai_phong_id) REFERENCES loaiphong(id)
);

CREATE TABLE datphong (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    check_in TIMESTAMP NOT NULL,
    check_out TIMESTAMP NOT NULL,
    trang_thai VARCHAR(50) DEFAULT 'PENDING',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE ct_datphong (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    datphong_id INTEGER NOT NULL,
    phong_id INTEGER NOT NULL,
    don_gia DECIMAL(18,2) NOT NULL,
    FOREIGN KEY (datphong_id) REFERENCES datphong(id),
    FOREIGN KEY (phong_id) REFERENCES phong(id),
    CONSTRAINT uq_ct_datphong UNIQUE (datphong_id, phong_id)
);

-- ===== PAYMENT =====
CREATE TABLE payments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id INTEGER NOT NULL,
    user_id INTEGER NOT NULL,
    amount DECIMAL(18,2) NOT NULL,
    method VARCHAR(50),
    status VARCHAR(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (booking_id) REFERENCES datphong(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE refunds (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_id INTEGER NOT NULL,
    refund_amount DECIMAL(18,2) NOT NULL,
    status VARCHAR(50),
    reason VARCHAR(255),
    approved_by INTEGER,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (payment_id) REFERENCES payments(id),
    FOREIGN KEY (approved_by) REFERENCES admins(id)
);
